uint64 term              # leader's term
uint32 leader_id         # so followers can redirect clients
uint64 prev_log_index    # index of log entry immediately preceeding new ones
uint64 prev_log_term     # term of prev_log_index
byte[] entries           # log entries to store (empty for heartbeat)
uint64 leader_commit     # leader's commitIndex
---
uint64 term              # current term, for leader to update itself
bool success             # true if follower contained entry matching
                         # prev_data_index and prev_data_term
