name: lint
on:
  push:
    branches: [ galactic, humble ]
  pull_request:
    branches: [ galactic, humble ]
jobs:
  clang-format-checker:
    name: clang-format checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: '.'
            exclude: 'foros/docs/foros.hpp' # Exclude doxygen mainpage
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path['check'] }}
        exclude-regex: ${{ matrix.path['exclude'] }}
        fallback-style: 'Google'
